query GetWorkItems {
  group(fullPath: "oceanbox") {
    workItems {
      nodes {
        id
        iid
        title
        state
        webUrl
        createdAt
        updatedAt
      }
    }
  }
}
